//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyManagementDataLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompanyManagementDataLayer.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Fields are present.
        /// </summary>
        internal static string AllFieldPresent {
            get {
                return ResourceManager.GetString("AllFieldPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id is Missing.
        /// </summary>
        internal static string ClientIdMissing {
            get {
                return ResourceManager.GetString("ClientIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Id is Missing.
        /// </summary>
        internal static string DepartmentIdMissing {
            get {
                return ResourceManager.GetString("DepartmentIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee  DepartmentId  Missing.
        /// </summary>
        internal static string EmployeeDepartmentIdMissing {
            get {
                return ResourceManager.GetString("EmployeeDepartmentIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Email Missing.
        /// </summary>
        internal static string EmployeeEmailMissing {
            get {
                return ResourceManager.GetString("EmployeeEmailMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Hire Date Missing.
        /// </summary>
        internal static string EmployeeHirDateMissing {
            get {
                return ResourceManager.GetString("EmployeeHirDateMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID Missing.
        /// </summary>
        internal static string EmployeeIdMissing {
            get {
                return ResourceManager.GetString("EmployeeIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Such Employee Exist in Database.
        /// </summary>
        internal static string EmployeeIdMissingDb {
            get {
                return ResourceManager.GetString("EmployeeIdMissingDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name is Missing.
        /// </summary>
        internal static string EmployeeNameMissing {
            get {
                return ResourceManager.GetString("EmployeeNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Phone Number Missing.
        /// </summary>
        internal static string EmployeePhoneNumberMissing {
            get {
                return ResourceManager.GetString("EmployeePhoneNumberMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Salary Missing.
        /// </summary>
        internal static string EmployeeSalaryMissing {
            get {
                return ResourceManager.GetString("EmployeeSalaryMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Such Technology Present.
        /// </summary>
        internal static string InvalidTechnologyId {
            get {
                return ResourceManager.GetString("InvalidTechnologyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager is Already Assigned.
        /// </summary>
        internal static string ManagerAlreadyAssigned {
            get {
                return ResourceManager.GetString("ManagerAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Id is missing.
        /// </summary>
        internal static string ProjectIDMissing {
            get {
                return ResourceManager.GetString("ProjectIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Such Project Exisit in Database.
        /// </summary>
        internal static string ProjectIdNotFound {
            get {
                return ResourceManager.GetString("ProjectIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manger ID not found.
        /// </summary>
        internal static string ProjectManagerIDMissing {
            get {
                return ResourceManager.GetString("ProjectManagerIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name is Missing.
        /// </summary>
        internal static string ProjectNameMissing {
            get {
                return ResourceManager.GetString("ProjectNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Id is Missing.
        /// </summary>
        internal static string StatusIdMissing {
            get {
                return ResourceManager.GetString("StatusIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Id is missing.
        /// </summary>
        internal static string TaskIdMissing {
            get {
                return ResourceManager.GetString("TaskIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Such Task Id Exist in Database.
        /// </summary>
        internal static string TaskIdMissingDb {
            get {
                return ResourceManager.GetString("TaskIdMissingDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name is missing.
        /// </summary>
        internal static string TaskNameMissing {
            get {
                return ResourceManager.GetString("TaskNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology is already assigned .
        /// </summary>
        internal static string TechnologyAlreadyAssigned {
            get {
                return ResourceManager.GetString("TechnologyAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Id missing.
        /// </summary>
        internal static string TechnologyIdMissing {
            get {
                return ResourceManager.GetString("TechnologyIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Such Technology Exist in Database.
        /// </summary>
        internal static string TechnologyIdMissingDb {
            get {
                return ResourceManager.GetString("TechnologyIdMissingDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Name is Missing.
        /// </summary>
        internal static string TechnologyNameMissing {
            get {
                return ResourceManager.GetString("TechnologyNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Version is Missing.
        /// </summary>
        internal static string TechnologyVersionMissing {
            get {
                return ResourceManager.GetString("TechnologyVersionMissing", resourceCulture);
            }
        }
    }
}
