//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyManagementBusinessLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompanyManagementBusinessLayer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Cannot Be Deleted As It is Running State.
        /// </summary>
        internal static string CannotDeleteRunningProject {
            get {
                return ResourceManager.GetString("CannotDeleteRunningProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Cannot Be Deleted As It is Running State.
        /// </summary>
        internal static string CannotDeleteRunningTask {
            get {
                return ResourceManager.GetString("CannotDeleteRunningTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete technology as it used in more than 2 projects.
        /// </summary>
        internal static string DeleteProjectError {
            get {
                return ResourceManager.GetString("DeleteProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Cannot Work For Project as Employee is working for max projects.
        /// </summary>
        internal static string EmployeeAssignmentError {
            get {
                return ResourceManager.GetString("EmployeeAssignmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string EmployeeAssignmentValue {
            get {
                return ResourceManager.GetString("EmployeeAssignmentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Assign Project As Project Manager is managing maximum Projects.
        /// </summary>
        internal static string ExcessProjectForManager {
            get {
                return ResourceManager.GetString("ExcessProjectForManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Assign Technology To Task as More than 4 Technology cannot be assigned.
        /// </summary>
        internal static string MoreTechnologyThanRequired {
            get {
                return ResourceManager.GetString("MoreTechnologyThanRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string ProjectAssignmentValue {
            get {
                return ResourceManager.GetString("ProjectAssignmentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Cannot Be Created on Completed Project.
        /// </summary>
        internal static string TaskCannotAssignCompletedProject {
            get {
                return ResourceManager.GetString("TaskCannotAssignCompletedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string TechnologyAssignmentValue {
            get {
                return ResourceManager.GetString("TechnologyAssignmentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Assign Technology To Task as Task is Not Assigned to Project.
        /// </summary>
        internal static string TechnologyNotInProject {
            get {
                return ResourceManager.GetString("TechnologyNotInProject", resourceCulture);
            }
        }
    }
}
